### ISSUE TITLE
Another project for CSV-to-YNAB conversion

### ISSUE THREAD

**Issue by torbengb** [Salem5/ConvertBankstatementForYNAB#1]
Hello Omar!
I've seen that you added a YNAB repository to GitHub, even if it's two years ago. Have you seen that there are many similar projects? There is one in particular that could be very interesting for you: "bank2ynab"

https://github.com/torbengb/bank2ynab/blob/develop/README.md

If you could provide a sample CSV export (anonymized) then we could easily create the converter for your bank, too! We would also like to know the default filename for the exported CSV, so we can identify it and use the proper converter. 

Let me know what you think!
Best regards from snowy Austria,
Ben

**Comment by iomeanslife** [comment]
Hi Ben,

I failed to notice this on time, sorry. I am using a different bank by now and I haven't looked into ynab either for years. I will archive this project, but thanks for reaching out anyway.

Regards
Omar
